// Adaptado de las dos hojas de instrucciones y la guía de legendarias del proyecto.
export const instructionsPromo = `<section class="section play-promo" aria-labelledby="play-title"><a class="play-art" href="instrucciones.html" aria-label="Abrir las instrucciones para jugar"><img class="sheet-back" src="assets/instrucciones/hoja-2-mini.webp" alt="" width="300" height="424" loading="lazy"><img class="sheet-front" src="assets/instrucciones/hoja-1-mini.webp" alt="Guía ilustrada de TAIKARDS" width="300" height="424" loading="lazy"><span class="play-seal" aria-hidden="true">📖</span></a><div><p class="eyebrow">ABRÍ EL LIBRO Y EMPEZÁ LA AVENTURA</p><h2 id="play-title">¿Primera partida?<br><em>¡Aprendamos a jugar!</em></h2><p>Prepará tus criaturas, elegí un nivel y desafiá a un amigo. Te acompañamos paso a paso.</p><div class="play-facts"><span>👥 2 jugadores</span><span>🏆 Primero en sumar 2 puntos</span></div><a class="button primary" href="instrucciones.html">Cómo jugar <span aria-hidden="true">→</span></a></div></section>`;

const matchups = [['🔥','Fuego','Bosque y Espíritu'],['💧','Agua','Fuego y Guardián'],['🌿','Bosque','Agua y Guardián'],['👻','Espíritu','Agua y Bosque'],['🦁','Guardián','Fuego y Espíritu']];
export const instructionsContent = `<main id="main" class="guide-main"><nav class="breadcrumbs" aria-label="Ruta de navegación"><a href="index.html">Inicio</a><span>/</span><span aria-current="page">Cómo jugar</span></nav>
<header class="guide-intro"><p class="eyebrow">EL LIBRO DE TU PRIMERA AVENTURA</p><h1>¡Vamos a <em>jugar!</em></h1><p>Buscá un compañero, prepará tus cartas y seguí estos pasos.</p><div class="play-facts"><span>👥 2 jugadores</span><span>🃏 Al menos 3 criaturas por jugador</span><span>🏆 Gana quien suma 2 puntos primero</span></div></header>
<nav class="guide-jumps" aria-label="Secciones de las instrucciones"><a href="#preparacion">1. Preparación</a><a href="#duelo">2. El duelo</a><a href="#niveles">3. Los niveles</a><a href="#desafios">Desempates</a><a href="#laminas">Guías ilustradas</a></nav>
<div class="guide-columns"><section class="guide-paper" id="preparacion"><p class="eyebrow">PASO 1</p><h2>Preparen sus cartas</h2><ol class="guide-steps"><li>Salúdense con una reverencia: <strong>¡Onegaishimasu!</strong></li><li>Siéntense en seiza y acuerden el nivel que van a jugar.</li><li>Cada jugador mezcla sus criaturas y deja su mazo <strong>boca abajo</strong>.</li><li>Dejen las cartas de efecto separadas. <strong>Solo se usan en el Nivel 3.</strong></li></ol><aside class="guide-note"><strong>🦁 Un tesoro para tu colección</strong><p>Las legendarias no se usan para combatir en ningún nivel: no dan puntos ni poderes. Sepárenlas de las criaturas y los efectos y guárdenlas fuera del mazo de juego.</p></aside></section>
<section class="guide-paper" id="duelo"><p class="eyebrow">PASO 2</p><h2>¡Hajime! Empieza el duelo</h2><ol class="guide-steps"><li>Cada jugador roba <strong>1 criatura al azar</strong> de su mazo.</li><li>Digan <strong>¡Hajime!</strong> y muestren las cartas al mismo tiempo.</li><li>Comparen las cartas según el nivel elegido.</li><li>Quien gana el duelo suma <strong>1 punto</strong>.</li><li>Las <strong>dos criaturas usadas quedan fuera</strong> hasta terminar la partida.</li></ol><div class="guide-victory"><span aria-hidden="true">🏆</span><strong>¡El primero en sumar<br>2 puntos gana!</strong></div></section></div>
<section id="niveles" class="guide-levels"><div class="section-heading"><div><p class="eyebrow">PASO 3 · ELIJAN ANTES DE EMPEZAR</p><h2>Tres formas de <em>jugar</em></h2></div><p>Cada nivel indica qué comparar.<br>Las cartas de campo se usan solo en el Nivel 3.</p></div>
<section class="guide-paper" id="nivel-1"><span class="level-label">NIVEL 1</span><h2>Combate</h2><p>Miren <strong>solo el símbolo de combate</strong> de cada carta.</p><div class="combat-rules" aria-label="Relaciones de combate"><div><strong><span class="combat-icon attack" aria-hidden="true">👊</span>Ataque</strong><span>vence a →</span><strong><span class="combat-icon speed" aria-hidden="true">⚡</span>Velocidad</strong></div><div><strong><span class="combat-icon speed" aria-hidden="true">⚡</span>Velocidad</strong><span>vence a →</span><strong><span class="combat-icon defense" aria-hidden="true">🛡</span>Defensa</strong></div><div><strong><span class="combat-icon defense" aria-hidden="true">🛡</span>Defensa</strong><span>vence a →</span><strong><span class="combat-icon attack" aria-hidden="true">👊</span>Ataque</strong></div></div><p class="tie-link">¿Mismo símbolo? <a href="#desafios">¡Hagan un desafío! ↓</a></p></section>
<section class="guide-paper" id="nivel-2"><span class="level-label">NIVEL 2</span><h2>Elementos</h2><p>Miren <strong>solo el elemento</strong>, también llamado naturaleza. Cada uno vence a estos dos:</p><table class="element-table"><caption class="sr-only">Ventajas de los cinco elementos</caption><thead><tr><th scope="col">Elemento</th><th scope="col">Vence a</th></tr></thead><tbody>${matchups.map(([icon,name,wins])=>`<tr><th scope="row"><span aria-hidden="true">${icon}</span> ${name}</th><td>${wins}</td></tr>`).join('')}</tbody></table><p class="tie-link">¿Mismo elemento? <a href="#desafios">¡Elijan un desafío! ↓</a></p></section>
<section class="guide-paper" id="nivel-3"><span class="level-label">NIVEL 3</span><h2>Combate + elementos + campos</h2><ol class="guide-steps"><li>Cada jugador roba <strong>1 carta de efecto al azar</strong>. Muéstrenlas antes del primer duelo.</li><li>Los dos campos afectan a <strong>ambos jugadores</strong> y duran <strong>toda la partida</strong>. Lean qué cambian.</li><li>Comparen <strong>combate</strong>. Si empatan, comparen <strong>elemento</strong>.</li><li>Si sigue el empate, apliquen los <strong>efectos de desempate</strong>. ¿Todavía empatados? <a href="#desafios">¡Desafío!</a></li></ol><aside class="guide-note"><strong>📜 Lo que dicen los campos importa</strong><ul><li>Las cartas de campo pueden cambiar las reglas normales.</li><li>Si un efecto anula al otro, no se roba otra carta.</li><li>Dos efectos iguales se aplican una sola vez.</li><li>Si ambos tienen el mismo beneficio o impedimento y siguen empatados, hagan un desafío.</li></ul></aside><div class="guide-examples"><article><h3>💧 Un empate en combate</h3><p>Sin efectos que cambien el resultado: Ataque contra Ataque empata. Si una criatura es Agua y la otra Fuego, <strong>¡Agua vence a Fuego!</strong></p></article><article><h3>🌙 Un campo anula a otro</h3><p><strong>Luna Llena anula Sol de Verano.</strong> El Sol no da su ventaja. ¡Se juega así!</p></article></div></section></section>
<section class="guide-paper" id="desafios"><p class="eyebrow">PARA RESOLVER UN EMPATE</p><h2>¡Elijan un desafío!</h2><p>Elijan juntos en ese momento:</p><div class="challenge-grid"><article><span aria-hidden="true">✊ ✋ ✌️</span><h3>Piedra, papel o tijera</h3><p>Jueguen para decidir quién gana el duelo.</p></article><article><span aria-hidden="true">👀</span><h3>Miradas</h3><p>Pierde quien pestañea primero.</p></article><article><span aria-hidden="true">😄</span><h3>Seriedad</h3><p>Pierde quien se ríe primero.</p></article></div><p class="guide-highlight">El ganador del desafío suma el punto del duelo. <strong>Si empatan, repitan.</strong></p></section>
<section class="guide-paper"><h2>¿Una partida más larga?</h2><p>Acuerden una de estas opciones <strong>antes de empezar</strong>:</p><div class="long-games"><div><h3>Mejor de 5</h3><p>Gana con <strong>3 puntos</strong><br>5 criaturas cada uno</p></div><div><h3>Mejor de 7</h3><p>Gana con <strong>4 puntos</strong><br>7 criaturas cada uno</p></div><div><h3>Mejor de 9</h3><p>Gana con <strong>5 puntos</strong><br>9 criaturas cada uno</p></div></div></section>
<section class="guide-sheets" id="laminas"><p class="eyebrow">TENÉ LAS REGLAS A MANO</p><h2>Las guías <em>ilustradas</em></h2><p>Tocá una hoja para abrirla en grande. También podés guardarla en tu celular.</p><div class="sheet-grid">${[1,2].map(n=>`<a href="assets/instrucciones/hoja-${n}.webp"><img src="assets/instrucciones/hoja-${n}-mini.webp" alt="Hoja ${n}: ${n===1?'preparación, duelos, combate y desafíos':'elementos, campos y partidas más largas'}" width="300" height="424" loading="lazy"><span>Hoja ${n} · ${n===1?'Empezá a jugar':'Otros niveles'} ↗</span></a>`).join('')}</div></section><div class="guide-finish"><h2>¿Todo listo? <em>¡Hajime!</em></h2><a class="button primary" href="index.html#coleccion">Explorá las cartas →</a></div></main>`;
