import {instructionsContent, instructionsPromo} from '../instructions.mjs';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {cards,icons,slugify} from '../data.mjs';
const root = fileURLToPath(new URL('../',import.meta.url));
const source = process.env.TAIKARDS_CARDS || path.resolve(root,'../../Cartas/Yokai/Completas');
const esc = s => String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
await fs.mkdir(path.join(root,'assets/cards'),{recursive:true});
await fs.mkdir(path.join(root,'yokai'),{recursive:true});
for(const c of cards){
 const full=path.join(root,'assets/cards',`${c.slug}.webp`), thumb=path.join(root,'assets/cards',`${c.slug}-thumb.webp`);
 try {await fs.access(full);await fs.access(thumb);} catch {
  // Normal builds use the optimized images committed to this repository.
  // Only importing new artwork requires sharp and the original card folder.
  const {default: sharp} = await import('sharp');
  await sharp(path.join(source,`${c.name}.png`)).resize({width:1060,withoutEnlargement:true}).webp({quality:88}).toFile(full);
  await sharp(path.join(source,`${c.name}.png`)).resize(420).webp({quality:80}).toFile(thumb);
 }
}
const badges = c => `<span class="badge ${slugify(c.nature)}">${icons[c.nature]} ${c.nature}</span><span class="badge type">${icons[c.type]} ${c.type}</span>`;
const tile = (c,base='') => `<article class="card" data-name="${esc(c.name)}" data-nature="${c.nature}" data-type="${c.type}"><a href="${base}yokai/${c.slug}.html" aria-label="Conocé a ${esc(c.name)}"><div class="card-image"><img src="${base}assets/cards/${c.slug}-thumb.webp" alt="Carta completa de ${esc(c.name)}" width="420" height="586" loading="lazy" decoding="async"><span class="card-open" aria-hidden="true">Conocé su historia ↗</span></div><div class="card-title"><h3>${c.name}</h3><span>${c.number}</span></div><p class="card-subtitle">${c.subtitle}</p><div class="badges">${badges(c)}</div></a></article>`;
const header = base => `<a class="skip" href="#main">Saltar al contenido</a><header class="header"><a class="brand" href="${base}index.html" aria-label="TAIKARDS, inicio"><img class="brand-logo" src="${base}assets/logo-taikards-360.webp" alt="TAIKARDS" width="360" height="125"></a><nav aria-label="Navegación principal"><a href="${base}index.html#coleccion">Las cartas</a><a class="how-to-link" href="${base}instrucciones.html">Cómo jugar</a><a href="${base}index.html#universo">El universo</a><a class="nav-accent" href="${base}index.html#shisa">Conocé a los Shisa <span aria-hidden="true">↗</span></a></nav></header>`;
const footer = base => `<footer><a class="footer-brand" href="${base}index.html"><img class="footer-logo" src="${base}assets/logo-taikards-360.webp" alt="TAIKARDS" width="360" height="125" loading="lazy"><span>El Juego de Cartas del Kodomo Taikai</span></a><p>Pequeñas cartas. Grandes aventuras.</p><a href="#top">Volver arriba ↑</a></footer>`;
const head = (title,description,base='')=>`<!doctype html><html lang="es-AR" id="top"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f5f0e5"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="icon" href="${base}assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${base}styles.css"><link rel="stylesheet" href="${base}kids.css"><link rel="stylesheet" href="${base}guide.css"><script defer src="${base}app.js"></script></head><body>${header(base)}`;
const home = `${head('TAIKARDS · El Juego de Cartas del Kodomo Taikai','Acompañá a los Shisa y descubrí las 48 cartas de yōkai: historias, naturaleza y tipo de cada criatura.')}<main id="main">
<section class="hero"><div class="hero-copy"><p class="eyebrow"><span></span> ¡TU AVENTURA EMPIEZA ACÁ!</p><h1 aria-label="TAIKARDS"><img class="hero-logo" src="assets/logo-taikards-1000.webp" alt="TAIKARDS" width="1000" height="347" fetchpriority="high"><span class="subtitle">El Juego de Cartas<br>del Kodomo Taikai</span></h1><p class="hero-description">Acompañá a los Shisa a conocer a todos los <strong>yōkai de Japón</strong> y, próximamente, las criaturas mitológicas de todo el mundo.</p><div class="hero-actions"><a class="button primary" href="#coleccion">¡Vamos a explorar! <span>↓</span></a><button class="text-button" data-random>🎲 ¡Sorprendeme!</button></div><div class="hero-stats"><div><strong>48</strong><span>cartas para descubrir</span></div><div><strong>5</strong><span>naturalezas</span></div><div><strong>∞</strong><span>historias por imaginar</span></div></div></div><div class="hero-art" aria-label="Cartas de Shisa Verde, Kitsune y Shisa Amarillo"><div class="sun"></div><span class="shisa-greeting">¡Hola! ¿Venís a jugar? ✨</span><img class="hero-card back-left" src="assets/cards/shisa-verde-thumb.webp" alt="Shisa Verde" width="420" height="586"><img class="hero-card back-right" src="assets/cards/kitsune-thumb.webp" alt="Kitsune" width="420" height="586"><img class="hero-card front" src="assets/cards/shisa-amarillo.webp" alt="Carta Shisa Amarillo, guardián del Kodomo Taikai" width="1060" height="1478" fetchpriority="high"><span class="art-caption">¡Los Shisa te están esperando!</span></div></section>
<div class="ribbon" aria-hidden="true"><span class="ribbon-message">✨ Descubrí criaturas increíbles</span><b>•</b><span class="ribbon-message">🌈 Elegí tus favoritas</span><b>•</b><span class="ribbon-message">🤝 Compartí la aventura</span></div>
${instructionsPromo}
<section class="collection section" id="coleccion"><div class="section-heading"><div><p class="eyebrow">🧭 TU ÁLBUM DE AVENTURAS</p><h2>¡Conocé a los <em>yōkai!</em></h2></div><p>¿A quién querés conocer hoy?<br>Tocá una carta y descubrí su historia.</p></div><div class="filters"><label class="search"><span aria-hidden="true">⌕</span><input type="search" id="search" placeholder="Buscá tu yōkai favorito…" aria-label="Buscar cartas por nombre"><kbd aria-hidden="true">/</kbd></label><label class="type-select">Tipo<select id="type"><option value="">Todos los tipos</option>${['Ataque','Defensa','Velocidad'].map(t=>`<option>${t}</option>`).join('')}</select></label></div><div class="filter-row"><div class="nature-filters" role="group" aria-label="Filtrar por naturaleza"><button class="filter active" data-nature-filter="" aria-pressed="true">Todos <span>48</span></button>${['Fuego','Agua','Bosque','Espíritu','Guardián'].map(n=>`<button class="filter" data-nature-filter="${n}" aria-pressed="false">${icons[n]} ${n} <span>${cards.filter(c=>c.nature===n).length}</span></button>`).join('')}</div><label class="sort-label">Orden<select id="sort"><option value="az">Nombre A–Z</option><option value="za">Nombre Z–A</option></select></label></div><div class="results-line"><p id="count" role="status" aria-live="polite">Mostrando 48 de 48 cartas</p><button id="clear" class="text-button" hidden>Limpiar filtros ×</button></div><div class="grid" id="cards">${[...cards].sort((a,b)=>a.name.localeCompare(b.name,'es')).map(c=>tile(c)).join('')}</div><div id="empty" class="empty" hidden><span>⌕</span><h3>Ese yōkai todavía se esconde.</h3><p>Probá con otro nombre o cambiá los filtros.</p><button class="button primary" id="reset">Ver todas las cartas</button></div><noscript><p>Podés explorar todas las cartas. Activá JavaScript para buscar y filtrar.</p></noscript></section>
<section class="universe section" id="universo"><div><p class="eyebrow">💡 UN MUNDO LLENO DE SORPRESAS</p><h2>¿Qué es un <em>yōkai?</em></h2><p>En las historias de Japón, hay criaturas que se esconden en los bosques, luces que bailan en la noche y hasta paraguas que cobran vida. A muchos de esos seres extraordinarios los llamamos <strong>yōkai</strong>.</p><p>Algunos son traviesos, otros misteriosos. En TAIKARDS, sus historias se transforman en una aventura para chicos: descubrir, imaginar y aprender juntos.</p><p class="editorial-note">Los relatos de estas fichas están adaptados a partir de nuestras cartas. Mezclan inspiración del folclore japonés con personajes y versiones del Kodomo Taikai; no son una reproducción literal de las leyendas.</p></div><div class="nature-guide"><p class="eyebrow">ENCONTRÁ TU NATURALEZA</p>${[['Fuego','Chispas, energía y sorpresas.'],['Agua','Un viaje entre ríos y mares.'],['Bosque','Los secretos de la naturaleza.'],['Espíritu','La magia de lo inesperado.'],['Guardián','Amigos que cuidan el camino.']].map(([n,t])=>`<a href="#coleccion" data-pick-nature="${n}"><span class="nature-icon ${slugify(n)}">${icons[n]}</span><span><strong>${n}</strong><small>${t}</small></span><span>↗</span></a>`).join('')}</div></section>
<section class="shisa-section section" id="shisa"><div class="shisa-picture"><img src="assets/cards/equipo-shisa-1.webp" alt="El equipo de Shisa Amarillo y Shisa Verde" width="1060" height="1478" loading="lazy"></div><div><p class="eyebrow">🌟 TUS AMIGOS SHISA</p><h2>Juntos somos<br><em>más fuertes.</em></h2><p>Desde Okinawa llegan los Shisa, nuestros guardianes del Kodomo Taikai. Con valentía, amistad y muchas ganas de aprender, te acompañan a descubrir un mundo increíble.</p><a class="button primary" href="yokai/equipo-shisa-1.html">Conocé al Equipo Shisa ↗</a><div class="coming-soon"><span>PRÓXIMAMENTE</span><h3>La aventura sigue alrededor del mundo.</h3><p>Nuevas criaturas mitológicas, cartas de efectos y legendarias. Todavía quedan muchas historias por descubrir.</p></div></div></section></main>${footer('')}</body></html>`;
await fs.writeFile(path.join(root,'index.html'),home);
await fs.writeFile(path.join(root,'instrucciones.html'), `${head('Cómo jugar · TAIKARDS','Aprendé a jugar TAIKARDS: preparación, duelos, tres niveles, elementos, campos y desafíos para resolver empates.')}${instructionsContent}${footer('')}</body></html>`);
for (let i=0;i<cards.length;i++){
 const c=cards[i],prev=cards[(i+cards.length-1)%cards.length],next=cards[(i+1)%cards.length];
 const related=cards.filter(r=>r.nature===c.nature&&r!==c).slice(0,4);
 const detail=`${head(`${c.name} · TAIKARDS`,c.subtitle+'. '+c.story.slice(0,130),'../')}<main id="main" class="detail-main"><nav class="breadcrumbs" aria-label="Ruta de navegación"><a href="../index.html">Inicio</a><span>/</span><a href="../index.html#coleccion">Las cartas</a><span>/</span><span aria-current="page">${c.name}</span></nav><article class="detail"><div class="detail-art"><a class="full-card" href="../assets/cards/${c.slug}.webp" data-zoom aria-label="Ampliar carta de ${c.name}"><img src="../assets/cards/${c.slug}.webp" alt="Carta completa de ${c.name}" width="1060" height="1478" fetchpriority="high"></a><p>↗ Tocá la carta para verla en grande</p></div><div class="detail-copy"><p class="eyebrow">EL ÁLBUM TAIKARDS <span>·</span> CARTA ${c.number} / 48</p><h1>${c.name}</h1><p class="detail-subtitle">${c.subtitle}</p><dl class="classification"><div><dt>Naturaleza / elemento</dt><dd>${icons[c.nature]} ${c.nature}</dd></div><div><dt>Tipo</dt><dd>${icons[c.type]} ${c.type}</dd></div></dl><h2>📖 Te cuento mi historia</h2><p class="story">${c.story}</p><aside class="activity"><span aria-hidden="true">✦</span><div><h3>💡 ¡Ahora te toca a vos!</h3><p>${c.activity}</p></div></aside><p class="editorial-note">Versión infantil basada en la carta de TAIKARDS. Sus personajes y aventuras pueden ser diferentes de las leyendas tradicionales. La naturaleza y el tipo corresponden a la clasificación del juego.</p><a class="back-link" href="../index.html#coleccion">← Volver a todas las cartas</a></div></article><nav class="card-pagination" aria-label="Explorar más cartas"><a href="${prev.slug}.html"><small>← CARTA ANTERIOR</small>${prev.name}</a><a href="${next.slug}.html"><small>SIGUIENTE CARTA →</small>${next.name}</a></nav><section class="related"><div class="section-heading"><div><p class="eyebrow">SEGUÍ LA AVENTURA</p><h2>Más de ${c.nature.toLowerCase()}<em>.</em></h2></div><a href="../index.html#coleccion">Ver el álbum completo ↗</a></div><div class="grid">${related.map(r=>tile(r,'../')).join('')}</div></section></main><dialog id="zoom"><button class="zoom-close" aria-label="Cerrar carta ampliada">Cerrar ×</button><img alt="Carta ampliada de ${c.name}" src="../assets/cards/${c.slug}.webp"></dialog>${footer('../')}</body></html>`;
 await fs.writeFile(path.join(root,'yokai',`${c.slug}.html`),detail);
}
console.log(`TAIKARDS: ${cards.length} fichas + inicio generados.`);
